name: threads
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  awesome_icons: ^1.1.0
  cached_network_image: ^3.2.3
  camera: ^0.10.5+2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_analytics: ^10.1.6
  firebase_auth: ^4.3.0
  firebase_database: ^10.0.16
  firebase_storage: ^11.0.16
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.1
  flutter_native_splash: ^2.2.18
  flutter_spinkit: ^5.2.0
  get_it: ^7.2.0
  google_sign_in: ^6.1.5
  iconsax: ^0.0.8
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  lottie: ^2.3.2
  path: ^1.8.2
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  provider: ^6.0.5
  shared_preferences: ^2.0.20
  sign_in_with_apple: ^5.0.0
  url_launcher: ^6.1.10
  flutter_launcher_icons: "^0.13.1"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/TOUTLAISSEcon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/

