// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdmzV5I9r3oHSpu6paUfdZ76Xl0G2BYCY',
    appId: '1:969675328331:web:368488a38119bde6da36ce',
    messagingSenderId: '969675328331',
    projectId: 'toutlaissecom',
    authDomain: 'toutlaissecom.firebaseapp.com',
    storageBucket: 'toutlaissecom.appspot.com',
    measurementId: 'G-ELNKM77XT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-vmMJCZ8XyrqWOUKLvVxjmwzySea_PAI',
    appId: '1:969675328331:android:277aadeed6daaf64da36ce',
    messagingSenderId: '969675328331',
    projectId: 'toutlaissecom',
    storageBucket: 'toutlaissecom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlPU_nfqXoKLXi1N8iNlK8PuJriDkKCNI',
    appId: '1:969675328331:ios:91d0c7c718677045da36ce',
    messagingSenderId: '969675328331',
    projectId: 'toutlaissecom',
    storageBucket: 'toutlaissecom.appspot.com',
    iosClientId: '969675328331-3m026e27ljdhbtacifd095p28j9i4bvo.apps.googleusercontent.com',
    iosBundleId: 'y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlPU_nfqXoKLXi1N8iNlK8PuJriDkKCNI',
    appId: '1:969675328331:ios:485c20d2ce22b4a5da36ce',
    messagingSenderId: '969675328331',
    projectId: 'toutlaissecom',
    storageBucket: 'toutlaissecom.appspot.com',
    iosClientId: '969675328331-rbn5emjtabvj9e52hma9k0raaesq0542.apps.googleusercontent.com',
    iosBundleId: 'com.threads.clone',
  );
}
